### ISSUE TITLE
tmElements_t has not been declared

### ISSUE THREAD

**Issue by marcolombardi-rm** [PaulStoffregen/DS1307RTC#10]
In DS1307RTC.h I included `#include <Time.h>` before  `#include <TimeLib.h>` and work propely with Arduino/Genuino boards and with ESP82666 based boards.

**Comment by PaulStoffregen** [comment]
Please provide a sample program which shows the error when used with Arduino's boards (not ESP)

**Comment by marcolombardi-rm** [comment]
All ESP8266 based boards. With SetTime, ReadTest and all programs that uses DS1307RTC library. 
Other solution, before `#include <TimeLib.h>` is this:
`#ifdef ESP8266
#include <Time.h>
#endif`

**Comment by PaulStoffregen** [comment]
Please post a complete program which I can copy and paste into the Arduino IDE and click Verify to see the problem.  Please tell me exactly which board Arduino board (not ESP) I must choose in Tools > Boards.

Just to be clear, I will *not* investigate this problem unless you provide a program I can copy and paste into Arduino.  A description of the problem without code to copy into Arduino is not enough.

**Comment by marcolombardi-rm** [comment]
Excuse me, there is no problem with AVR based boards.

Problems are with all ESP8266 based boards. With SetTime, ReadTest and all programs that uses DS1307RTC library. Other solution, before #include <TimeLib.h> is this:
#ifdef ESP8266 #include <Time.h> #endif

**Comment by PaulStoffregen** [comment]
no code posted, closing this issue
