### ISSUE TITLE
TimeLib.h: No such file or directory

### ISSUE THREAD

**Issue by vindhyachaltakniki** [PaulStoffregen/DS1307RTC#7]
I have download library from: http://www.pjrc.com/teensy/td_libs_DS1307RTC.html
I am using arduino 1.6.5 & atmega2560 R3. Upon building I got error:
TimeLib.h: No such file or directory

**Comment by PaulStoffregen** [comment]
You also need the Time library.

**Comment by vindhyachaltakniki** [comment]
From where to add it?

**Comment by PaulStoffregen** [comment]
https://www.arduino.cc/en/Guide/Libraries#toc3

This issue tracking is NOT the place to ask for support.  It is meant for reporting software bugs.

Post your tech support questions on Arduino's forum, NOT here.
